version: '3'
services:
  dynamo:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    networks:
      - mynet
  api:
    image: "aspnetapp"
    ports:
      - "8080:80"
    networks:
      - mynet
networks:
  mynet: